name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Pull image as cache
        run: |
          docker pull ghcr.io/eol-virtuallabx/edx-platform:juniper || true

      - name: Build Open edX Base
        run: docker build . --file .github/build/Dockerfile --target base --build-arg EDX_PLATFORM_VERSION=${GITHUB_SHA} --tag ghcr.io/eol-virtuallabx/edx-platform:koa-${GITHUB_SHA} --tag ghcr.io/eol-virtuallabx/edx-platform:koa

      - name: Build Open edX testing version
        run: docker build . --file .github/build/Dockerfile --target testing --build-arg EDX_PLATFORM_VERSION=${GITHUB_SHA} --tag ghcr.io/eol-virtuallabx/edx-platform:test-${GITHUB_SHA} --tag ghcr.io/eol-virtuallabx/edx-platform:test

      - name: Push Hash
        run: |
          echo "${CR_PAT}" | docker login ghcr.io -u eol-vl --password-stdin
          docker push ghcr.io/eol-virtuallabx/edx-platform:koa-${GITHUB_SHA}
          docker push ghcr.io/eol-virtuallabx/edx-platform:test-${GITHUB_SHA}
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      
      - name: Push to koa
        if: github.ref == 'refs/heads/eol/koa.master'
        run: |
          echo "${CR_PAT}" | docker login ghcr.io -u eol-vl --password-stdin
          docker push ghcr.io/eol-virtuallabx/edx-platform:koa
          docker push ghcr.io/eol-virtuallabx/edx-platform:test
        env:
          CR_PAT: ${{ secrets.CR_PAT }}

      #- name: Trigger upload only on the correct branch
      #  if: github.ref == 'refs/heads/eol/juniper.master'
      #  run: |
      #    curl -XPOST -u "eol-vl:${{ secrets.CR_PAT }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/eol-virtuallabx/edx-argocd/dispatches --data '{"event_type": "update-images", "client_payload": {"type": "virtuallabx"}}'
